version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
